import Database from "better-sqlite3";
import fs from "fs";
import path from "path";

/**
 * Phase 0 schema bootstrapper — creates tables via raw SQL.
 *
 * In production, drizzle-kit generates migrations in the /drizzle directory.
 * For Phase 0 MVP, we bootstrap directly from a SQL file generated by drizzle-kit.
 */
const BOOTSTRAP_SQL = `
CREATE TABLE IF NOT EXISTS \`ai_config\` (
  \`id\` integer PRIMARY KEY AUTOINCREMENT,
  \`provider_url\` text NOT NULL DEFAULT 'https://api.openai.com/v1',
  \`api_key\` text NOT NULL DEFAULT '',
  \`model_name\` text NOT NULL DEFAULT 'gpt-4o',
  \`user_preferences\` text,
  \`created_at\` text NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS \`projects\` (
  \`id\` integer PRIMARY KEY AUTOINCREMENT,
  \`name\` text NOT NULL,
  \`status\` text NOT NULL DEFAULT 'pre_launch',
  \`repo_url\` text NOT NULL,
  \`repo_source\` text NOT NULL DEFAULT 'github_public',
  \`ai_product_summary\` text,
  \`ai_summary_generated_at\` text,
  \`created_at\` text NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS \`posts\` (
  \`id\` integer PRIMARY KEY AUTOINCREMENT,
  \`project_id\` integer NOT NULL REFERENCES \`projects\`(\`id\`) ON DELETE CASCADE,
  \`platform\` text NOT NULL DEFAULT 'twitter',
  \`title\` text NOT NULL,
  \`body\` text NOT NULL,
  \`platform_post_id\` text,
  \`permalink\` text,
  \`publish_mode\` text NOT NULL DEFAULT 'web_intent',
  \`status\` text NOT NULL DEFAULT 'draft',
  \`published_at\` text,
  \`created_at\` text NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS \`post_analytics\` (
  \`id\` integer PRIMARY KEY AUTOINCREMENT,
  \`post_id\` integer NOT NULL REFERENCES \`posts\`(\`id\`) ON DELETE CASCADE,
  \`platform\` text NOT NULL DEFAULT 'twitter',
  \`view_count\` integer,
  \`like_count\` integer,
  \`comment_count\` integer,
  \`share_count\` integer,
  \`source\` text NOT NULL DEFAULT 'manual',
  \`note\` text,
  \`fetched_at\` text NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS \`ai_actions\` (
  \`id\` integer PRIMARY KEY AUTOINCREMENT,
  \`project_id\` integer NOT NULL REFERENCES \`projects\`(\`id\`) ON DELETE CASCADE,
  \`action_type\` text NOT NULL,
  \`input_context\` text,
  \`output_content\` text,
  \`prompt_tokens\` integer,
  \`completion_tokens\` integer,
  \`estimated_cost\` real,
  \`user_modified\` integer DEFAULT 0,
  \`platform_post_id\` text,
  \`created_at\` text NOT NULL DEFAULT (datetime('now'))
);
`;

/**
 * Run the Phase 0 schema bootstrap against an existing database connection.
 * Idempotent — uses IF NOT EXISTS on every table.
 */
export function runMigrations(database: Database.Database) {
  database.exec(BOOTSTRAP_SQL);
}

/**
 * Convenience: create a database, run migrations, return drizzle instance.
 * Used by the Electron main process at app startup.
 */
export async function initDatabase(dbPath: string) {
  const { createDatabase } = await import("./index.js");
  const db = createDatabase(dbPath);
  // Access the underlying better-sqlite3 connection to run raw SQL
  const sqlite = (db as any).session?.client as Database.Database | undefined;
  if (sqlite) {
    runMigrations(sqlite);
  }
  return db;
}
